# Generated by Django 5.0.1 on 2024-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=255)),
                ("p_image", models.FileField(upload_to="products")),
                ("p_price", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="con_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="register",
            name="reg_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="register",
            name="reg_phone",
            field=models.TextField(),
        ),
    ]
