# Generated by Django 5.0.1 on 2024-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_product_alter_contact_con_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cp_name", models.CharField(max_length=255)),
                ("cp_qty", models.IntegerField()),
                ("cp_price", models.FloatField()),
                ("cp_total", models.FloatField()),
            ],
        ),
    ]
