# Generated by Django 5.0.1 on 2024-03-18 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_cart_cp_user_order_odr_status_order_odr_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
