# Generated by Django 5.0.1 on 2024-03-18 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_delete_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
