# Generated by Django 5.0.1 on 2024-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_video_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminlogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_name", models.CharField(max_length=255)),
                ("ad_uname", models.CharField(max_length=255)),
                ("ad_pwd", models.CharField(max_length=255)),
            ],
        ),
    ]
